<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QRPNPOQ" failures="0" tests="1" name="api.test.Test_Store_DD1" time="1.926" errors="1" timestamp="2025-09-17T18:12:44 IST" skipped="0">
  <testcase classname="api.test.Test_Store_DD1" name="Test_PlaceOrder_post" time="1.926">
    <error message="
[public void api.test.Test_Store_DD1.Test_PlaceOrder_post(int,int,int,java.lang.String,java.lang.String,boolean)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: Test_PlaceOrder_post([int id, int petId, int quantity, java.lang.String shipDate, java.lang.String status, boolean complete])
Arguments: [(java.lang.String) 1,(java.lang.String) 101,(java.lang.String) 2,(java.lang.String) 2025-09-16T16:10:09.458Z,(java.lang.String) placed,(java.lang.String) TRUE]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void api.test.Test_Store_DD1.Test_PlaceOrder_post(int,int,int,java.lang.String,java.lang.String,boolean)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: Test_PlaceOrder_post([int id, int petId, int quantity, java.lang.String shipDate, java.lang.String status, boolean complete])
Arguments: [(java.lang.String) 1,(java.lang.String) 101,(java.lang.String) 2,(java.lang.String) 2025-09-16T16:10:09.458Z,(java.lang.String) placed,(java.lang.String) TRUE]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Test_PlaceOrder_post -->
</testsuite> <!-- api.test.Test_Store_DD1 -->
